[versions]
android-plugin = "8.3.0"
jetbrains-kotlin-plugin = "1.9.22"
jetbrains-compose-plugin = "1.6.0"

androidx-appcompat = "1.6.1"
androidx-activity-compose = "1.8.2"
androidx-lifecycle-viewmodel-compose = "2.7.0"

google-material = "1.11.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }

jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrains-kotlin-plugin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlin-plugin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose-plugin" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-viewmodel-compose" }

google-material = { module = "com.google.android.material:material", version.ref = "google-material" }