name: Package

on:
  push:
    branches: [ master ]
    paths:
      - "**/WorkflowsTrigger.kt"

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
          cache: gradle

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: assembleRelease
        run: ./gradlew composeApp:assembleRelease

      - name: packageReleaseMsi
        run: ./gradlew composeApp:packageReleaseMsi

      - name: get current time
        uses: josStorer/get-current-time@v2
        id: currentTime
        with:
          format: YYYY.MM.DD
          utcOffset: "+08:00"

      - name: create a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/*.apk,**/*.msi"
          body: "create by workflows"
          allowUpdates: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: false
          token: ${{ secrets.ACTION_TOKEN }}
          tag: ${{ steps.currentTime.outputs.formattedTime }}
          name: v${{ steps.currentTime.outputs.formattedTime }}